# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
#- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
#  'require':
#    'frameworks/extra-cmake-modules': '@stable'
#    'frameworks/kcoreaddons': '@stable'
#    'frameworks/ki18n': '@stable'
#    'frameworks/kxmlgui': '@stable'
#    'frameworks/kconfigwidgets': '@stable'
#    'frameworks/kcrash': '@stable'
#    'frameworks/kdoctools': '@stable'
#    'education/marble': '@stable'
#    'graphics/libkexiv2': '@stable'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kcolorscheme': '@latest-kf6'
    'education/marble': '@latest-kf6'
    'graphics/libkexiv2': '@latest-kf6'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
