# SPDX-FileCopyrightText: none
#
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kcoreaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kcrash': '@stable'
    'graphics/libkexiv2': '@same'
    'kde/education/marble': '@stable'
