# SPDX-FileCopyrightText: none
#
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/*': '@stable'
    'graphics/libkexiv2': '@stable'
    'education/marble': '@stable'
