# SPDX-FileCopyrightText: 2024-2026 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: kgeotag
confinement: strict
grade: stable
base: core24
adopt-info: kgeotag
apps:
  kgeotag:
    extensions:
      - kde-neon-6
    common-id: org.kde.kgeotag
    desktop: usr/share/applications/org.kde.kgeotag.desktop
    command: usr/bin/kgeotag
    plugs:
      - audio-playback
      - browser-support
      - udisks2
      - mount-observe
      - home
    environment:
      QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/marble/plugins:$SNAP/usr/lib/x86_64-linux-gnu/plugins:/snap/kf6-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins"
layout:
  /usr/share/marble:
    symlink: $SNAP/usr/share/marble
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/marble:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/marble
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.kgeotag
    bus: session
parts:
  wayland:
    source: https://gitlab.freedesktop.org/wayland/wayland.git
    source-branch: 1.23
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - meson
      - pkgconf
      - xsltproc
      - xmlto
      - libexpat1-dev
      - libffi-dev
      - libxml2-dev
      - doxygen
      - graphviz
    build-environment:
      - PKG_CONFIG_PATH: "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/snap/kde-qt6-core24-sdk/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/snap/kf6-core24-sdk/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig"
  wayland-protocols:
    after:
      - wayland
    source: https://gitlab.freedesktop.org/wayland/wayland-protocols.git
    source-tag: 1.47
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - libwayland-dev
      - meson
      - pkgconf
    build-environment:
      - PKG_CONFIG_PATH: "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/snap/kde-qt6-core24-sdk/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/snap/kf6-core24-sdk/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig"
      - LD_LIBRARY_PATH: "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$LD_LIBRARY_PATH"
  libplasma:
    after: [wayland-protocols]
    source: https://invent.kde.org/plasma/libplasma.git
    source-branch: Plasma/6.6
    plugin: cmake
    build-packages:
      - libpulse0
      - libxkbcommon-dev
      - rsync
    stage-packages:
      - libpulse0
      - libxkbcommon0
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DENABLE_QT5=OFF
      - -DENABLE_QT6=ON
      - -DBUILD_TESTING=OFF
    override-build: |
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
    prime:
      - -usr/bin/rsync
  marble:
    after:
      - libplasma
    source: https://invent.kde.org/education/marble.git
    source-branch: master
    plugin: cmake
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - libpulse0
      - rsync
      - libshp-dev
      - libgps-dev
      - libwlocate-dev
      - libabsl-dev
      - libprotobuf-dev
      - protobuf-compiler
      - pkg-config
      - libdrm2
    stage-packages:
      - libpulse0
      - libshp4
      - libgps30t64
      - libwlocate0
      - libabsl20220623t64
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DENABLE_QT5=OFF
      - -DENABLE_QT6=ON
      - -DBUILD_TESTING=OFF
    override-pull: |
        craftctl default
        patch -p0 < ${SNAPCRAFT_PROJECT_DIR}/snap/local/patches/disable_broken_osm_plugin.patch
    stage:
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libz.so*
    override-build: |
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
    build-environment:
      - DICPATH: "$CRAFT_STAGE/usr/share/hunspell"
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:/snap/kf6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr
      - PKG_CONFIG_PATH: /snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
    prime:
      - -usr/bin/rsync
  kgeotag:
    after:
      - marble
    parse-info:
      - usr/share/metainfo/org.kde.kgeotag.appdata.xml
    plugin: cmake
    source: .
    source-type: local
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  gpu-2404:
    after: [kgeotag]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - kgeotag
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done

